# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Fibonacci appl

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install dependecies
      run: pip install pytest

    - name: Run tests
      run: pytest -v
      
  build-and-deploy:
      runs-on: ubuntu-latest
      needs: test  # Only run if tests pass
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Build Docker image
          run: docker build -t fibonacci-app .
  
        - name: Run Docker image
          run: docker run fibonacci-app
